-- MySQL Script generated by MySQL Workbench
-- Fri Sep 22 11:08:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgcm_aq3012514
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `especialidades` (
  `codigo_especialidade` INT NOT NULL,
  `descricao_especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_especialidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `medicos` (
  `codigo_medico` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `crm` VARCHAR(20) NULL,
  `codigo_especialidade` INT NOT NULL,
  PRIMARY KEY (`codigo_medico`),
  INDEX `fk_medicos_especialidades1_idx` (`codigo_especialidade` ASC) VISIBLE,
  CONSTRAINT `fk_medicos_especialidades1`
    FOREIGN KEY (`codigo_especialidade`)
    REFERENCES `especialidades` (`codigo_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `codigo_usuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `rg` VARCHAR(15) NULL,
  `cpf` VARCHAR(45) NULL,
  `rua` VARCHAR(40) NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(15) NULL,
  `bairro` VARCHAR(25) NULL,
  `cidade` VARCHAR(40) NULL,
  `estado` VARCHAR(2) NULL,
  `cep` VARCHAR(15) NULL,
  `telefone_fixo` VARCHAR(35) NULL,
  `telefone_celular` VARCHAR(35) NULL,
  `senha_acesso` VARCHAR(45) NULL,
  `permissao` VARCHAR(45) NULL,
  `identificacao_usuario` VARCHAR(20) NULL,
  `cadastro_usuario` VARCHAR(1) NULL,
  `cadastro_paciente` VARCHAR(1) NULL,
  `cadastro_especialidae` VARCHAR(1) NULL,
  `cadastro_medico` VARCHAR(1) NULL,
  `cadastro_convenio` VARCHAR(1) NULL,
  `agendamento_consulta` VARCHAR(1) NULL,
  `modulo_administrativo` VARCHAR(1) NULL,
  `modulo_agendamento` VARCHAR(1) NULL,
  `modulo_atendimento` VARCHAR(1) NULL,
  `data_nascimento` DATE NULL,
  `orgao_emissor` VARCHAR(6) NULL,
  PRIMARY KEY (`codigo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `convenio` (
  `codigo_convenio` INT NOT NULL,
  `empresa_convenio` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo_convenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paciente` (
  `codigo_paciente` INT NOT NULL,
  `identificacao_paciente` VARCHAR(20) NULL,
  `senha_acesso` VARCHAR(45) NULL,
  `nome_paciente` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `rg` VARCHAR(15) NULL,
  `orgao_emissor` VARCHAR(6) NULL,
  `cpf` VARCHAR(45) NULL,
  `rua` VARCHAR(40) NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(25) NULL,
  `cidade` VARCHAR(40) NULL,
  `estado` VARCHAR(2) NULL,
  `telefone_fixo` VARCHAR(35) NULL,
  `telefone_celular` VARCHAR(45) NULL,
  `convenio_codigo_convenio` INT NOT NULL,
  PRIMARY KEY (`codigo_paciente`, `convenio_codigo_convenio`),
  INDEX `fk_paciente_convenio1_idx` (`convenio_codigo_convenio` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_convenio1`
    FOREIGN KEY (`convenio_codigo_convenio`)
    REFERENCES `convenio` (`codigo_convenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agenda_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda_consulta` (
  `codigo_consulta` INT NOT NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  `retorno` VARCHAR(1) NULL,
  `cancelado` VARCHAR(1) NULL,
  `motivo_cancelamento` TEXT(500) NULL,
  `usuario_codigo_usuario` INT NOT NULL,
  `medicos_codigo_medico` INT NOT NULL,
  `paciente_codigo_paciente` INT NOT NULL,
  PRIMARY KEY (`codigo_consulta`, `usuario_codigo_usuario`, `medicos_codigo_medico`, `paciente_codigo_paciente`),
  INDEX `fk_agenda_consulta_usuario1_idx` (`usuario_codigo_usuario` ASC) VISIBLE,
  INDEX `fk_agenda_consulta_paciente1_idx` (`paciente_codigo_paciente` ASC) VISIBLE,
  INDEX `fk_agenda_consulta_medicos1_idx` (`medicos_codigo_medico` ASC) VISIBLE,
  CONSTRAINT `fk_agenda_consulta_usuario1`
    FOREIGN KEY (`usuario_codigo_usuario`)
    REFERENCES `usuario` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_consulta_paciente1`
    FOREIGN KEY (`paciente_codigo_paciente`)
    REFERENCES `paciente` (`codigo_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_consulta_medicos1`
    FOREIGN KEY (`medicos_codigo_medico`)
    REFERENCES `medicos` (`codigo_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prontuario_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prontuario_paciente` (
  `codigo_prontuario` INT NOT NULL,
  `historico` TEXT(500) NULL,
  `receituario` TEXT(500) NULL,
  `exames` TEXT(500) NULL,
  `agenda_consulta_codigo_consulta` INT NOT NULL,
  PRIMARY KEY (`codigo_prontuario`, `agenda_consulta_codigo_consulta`),
  INDEX `fk_prontuario_paciente_agenda_consulta1_idx` (`agenda_consulta_codigo_consulta` ASC) VISIBLE,
  CONSTRAINT `fk_prontuario_paciente_agenda_consulta1`
    FOREIGN KEY (`agenda_consulta_codigo_consulta`)
    REFERENCES `agenda_consulta` (`codigo_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `especialidades`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `especialidades` (`codigo_especialidade`, `descricao_especialidade`) VALUES (1, 'Acupuntura');
INSERT INTO `especialidades` (`codigo_especialidade`, `descricao_especialidade`) VALUES (2, 'Cardiologia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `convenio`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `convenio` (`codigo_convenio`, `empresa_convenio`, `cnpj`, `telefone`) VALUES (1, 'Sua Saúde', '97.279.798/0001-94', '(16) 3763-4499');
INSERT INTO `convenio` (`codigo_convenio`, `empresa_convenio`, `cnpj`, `telefone`) VALUES (2, 'Alto Padrão', '84.501.721/0001-75', '(16)3652-7962');

COMMIT;

