-- MySQL Script generated by MySQL Workbench
-- Tue Oct 17 18:37:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgcm_aq3012514
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgcm_aq3012514
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgcm_aq3012514` ;
USE `sgcm_aq3012514` ;

-- -----------------------------------------------------
-- Table `sgcm_aq3012514`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_aq3012514`.`especialidades` (
  `codigo_especialidade` INT NOT NULL,
  `descricao_especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_especialidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_aq3012514`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_aq3012514`.`medicos` (
  `codigo_medico` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `crm` VARCHAR(20) NULL,
  `codigo_especialidade` INT NOT NULL,
  PRIMARY KEY (`codigo_medico`),
  INDEX `fk_medicos_especialidades1_idx` (`codigo_especialidade` ASC) VISIBLE,
  CONSTRAINT `fk_medicos_especialidades1`
    FOREIGN KEY (`codigo_especialidade`)
    REFERENCES `sgcm_aq3012514`.`especialidades` (`codigo_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_aq3012514`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_aq3012514`.`usuario` (
  `codigo_usuario` INT NOT NULL,
  `identificacao_usuario` VARCHAR(20) NULL,
  `senha_acesso` VARCHAR(10) NULL,
  `cadastro_usuario` VARCHAR(1) NULL,
  `cadastro_paciente` VARCHAR(1) NULL,
  `cadastro_especialidade` VARCHAR(1) NULL,
  `cadastro_medico` VARCHAR(1) NULL,
  `cadastro_convenio` VARCHAR(1) NULL,
  `agendamento_consulta` VARCHAR(1) NULL,
  `modulo_administrativo` VARCHAR(1) NULL,
  `modulo_agendamento` VARCHAR(1) NULL,
  `modulo_atendimento` VARCHAR(1) NULL,
  `nome_completo` VARCHAR(50) NULL,
  `data_nascimento` VARCHAR(10) NULL,
  `numero_rg` VARCHAR(12) NULL,
  `orgao_emissor` VARCHAR(6) NULL,
  `numero_cpf` VARCHAR(14) NULL,
  `endereco` VARCHAR(45) NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(15) NULL,
  `bairro` VARCHAR(25) NULL,
  `cidade` VARCHAR(40) NULL,
  `estado` VARCHAR(2) NULL,
  `telefone` VARCHAR(20) NULL,
  `celular` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_aq3012514`.`convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_aq3012514`.`convenio` (
  `codigo_convenio` INT NOT NULL,
  `empresa_convenio` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo_convenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_aq3012514`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_aq3012514`.`paciente` (
  `codigo_paciente` INT NOT NULL,
  `identificacao_paciente` VARCHAR(20) NULL,
  `senha_acesso` VARCHAR(45) NULL,
  `nome_paciente` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `rg` VARCHAR(15) NULL,
  `orgao_emissor` VARCHAR(6) NULL,
  `cpf` VARCHAR(45) NULL,
  `rua` VARCHAR(40) NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(25) NULL,
  `cidade` VARCHAR(40) NULL,
  `estado` VARCHAR(2) NULL,
  `telefone_fixo` VARCHAR(35) NULL,
  `telefone_celular` VARCHAR(45) NULL,
  `convenio_codigo_convenio` INT NOT NULL,
  PRIMARY KEY (`codigo_paciente`, `convenio_codigo_convenio`),
  INDEX `fk_paciente_convenio1_idx` (`convenio_codigo_convenio` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_convenio1`
    FOREIGN KEY (`convenio_codigo_convenio`)
    REFERENCES `sgcm_aq3012514`.`convenio` (`codigo_convenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_aq3012514`.`agenda_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_aq3012514`.`agenda_consulta` (
  `codigo_consulta` INT NOT NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  `retorno` VARCHAR(1) NULL,
  `cancelado` VARCHAR(1) NULL,
  `motivo_cancelamento` TEXT(500) NULL,
  `usuario_codigo_usuario` INT NOT NULL,
  `medicos_codigo_medico` INT NOT NULL,
  `paciente_codigo_paciente` INT NOT NULL,
  PRIMARY KEY (`codigo_consulta`, `usuario_codigo_usuario`, `medicos_codigo_medico`, `paciente_codigo_paciente`),
  INDEX `fk_agenda_consulta_usuario1_idx` (`usuario_codigo_usuario` ASC) VISIBLE,
  INDEX `fk_agenda_consulta_paciente1_idx` (`paciente_codigo_paciente` ASC) VISIBLE,
  INDEX `fk_agenda_consulta_medicos1_idx` (`medicos_codigo_medico` ASC) VISIBLE,
  CONSTRAINT `fk_agenda_consulta_usuario1`
    FOREIGN KEY (`usuario_codigo_usuario`)
    REFERENCES `sgcm_aq3012514`.`usuario` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_consulta_paciente1`
    FOREIGN KEY (`paciente_codigo_paciente`)
    REFERENCES `sgcm_aq3012514`.`paciente` (`codigo_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_consulta_medicos1`
    FOREIGN KEY (`medicos_codigo_medico`)
    REFERENCES `sgcm_aq3012514`.`medicos` (`codigo_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_aq3012514`.`prontuario_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_aq3012514`.`prontuario_paciente` (
  `codigo_prontuario` INT NOT NULL,
  `historico` TEXT(500) NULL,
  `receituario` TEXT(500) NULL,
  `exames` TEXT(500) NULL,
  `agenda_consulta_codigo_consulta` INT NOT NULL,
  PRIMARY KEY (`codigo_prontuario`, `agenda_consulta_codigo_consulta`),
  INDEX `fk_prontuario_paciente_agenda_consulta1_idx` (`agenda_consulta_codigo_consulta` ASC) VISIBLE,
  CONSTRAINT `fk_prontuario_paciente_agenda_consulta1`
    FOREIGN KEY (`agenda_consulta_codigo_consulta`)
    REFERENCES `sgcm_aq3012514`.`agenda_consulta` (`codigo_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sgcm_aq3012514`.`especialidades`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_aq3012514`;
INSERT INTO `sgcm_aq3012514`.`especialidades` (`codigo_especialidade`, `descricao_especialidade`) VALUES (1, 'Acupuntura');
INSERT INTO `sgcm_aq3012514`.`especialidades` (`codigo_especialidade`, `descricao_especialidade`) VALUES (2, 'Cardiologia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgcm_aq3012514`.`medicos`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_aq3012514`;
INSERT INTO `sgcm_aq3012514`.`medicos` (`codigo_medico`, `nome`, `crm`, `codigo_especialidade`) VALUES (1, 'Aline Regina das Neves', '36641-SP', 1);
INSERT INTO `sgcm_aq3012514`.`medicos` (`codigo_medico`, `nome`, `crm`, `codigo_especialidade`) VALUES (2, 'Julio Cláudio Galvão', '23467-SP', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgcm_aq3012514`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_aq3012514`;
INSERT INTO `sgcm_aq3012514`.`usuario` (`codigo_usuario`, `identificacao_usuario`, `senha_acesso`, `cadastro_usuario`, `cadastro_paciente`, `cadastro_especialidade`, `cadastro_medico`, `cadastro_convenio`, `agendamento_consulta`, `modulo_administrativo`, `modulo_agendamento`, `modulo_atendimento`, `nome_completo`, `data_nascimento`, `numero_rg`, `orgao_emissor`, `numero_cpf`, `endereco`, `numero`, `complemento`, `bairro`, `cidade`, `estado`, `telefone`, `celular`) VALUES (1, 'admin', 'Senha123', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'Marli Raimunda Milena da Costa', '07/10/1989', '20.382.292-4', 'SSP/RS', '810.743.414-57', 'Rua Gustavo Peixoto', '533', 'CASA', 'Tibiriça', 'Cachoeira do Sul', 'RS', '(51) 2812-0587', '(51) 98616-6839');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgcm_aq3012514`.`convenio`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_aq3012514`;
INSERT INTO `sgcm_aq3012514`.`convenio` (`codigo_convenio`, `empresa_convenio`, `cnpj`, `telefone`) VALUES (1, 'Sua Saúde', '97.279.798/0001-94', '(16) 3763-4499');
INSERT INTO `sgcm_aq3012514`.`convenio` (`codigo_convenio`, `empresa_convenio`, `cnpj`, `telefone`) VALUES (2, 'Alto Padrão', '84.501.721/0001-75', '(16)3652-7962');

COMMIT;

