/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author aluno
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuAdministrativo = new javax.swing.JMenu();
        jMenuItemConsultaConvenios = new javax.swing.JMenuItem();
        jMenuItemConsultaEspecialidades = new javax.swing.JMenuItem();
        jMenuItemConsultaMedicos = new javax.swing.JMenuItem();
        jMenuItemConsultaUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadastroConvenios = new javax.swing.JMenuItem();
        jMenuItemCadastroEspecialidades = new javax.swing.JMenuItem();
        jMenuItemCadastroMedicos = new javax.swing.JMenuItem();
        jMenuItemCadastroUsuarios = new javax.swing.JMenuItem();
        jMenuAgendamento = new javax.swing.JMenu();
        jMenuAtendimento = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Clínica Médica");

        jPanelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jMenuAdministrativo.setText("Administrativo");

        jMenuItemConsultaConvenios.setText("Consulta Convênios");
        jMenuItemConsultaConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaConveniosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaConvenios);

        jMenuItemConsultaEspecialidades.setText("Consulta Especialidades");
        jMenuItemConsultaEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaEspecialidadesActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaEspecialidades);

        jMenuItemConsultaMedicos.setText("Consulta Médicos");
        jMenuItemConsultaMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaMedicosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaMedicos);

        jMenuItemConsultaUsuarios.setText("Consulta Usuários");
        jMenuItemConsultaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaUsuariosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemConsultaUsuarios);
        jMenuAdministrativo.add(jSeparator1);

        jMenuItemCadastroConvenios.setText("Cadastro Convênios");
        jMenuItemCadastroConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroConveniosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroConvenios);

        jMenuItemCadastroEspecialidades.setText("Cadastro Especialidades");
        jMenuItemCadastroEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroEspecialidadesActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroEspecialidades);

        jMenuItemCadastroMedicos.setText("Cadastro Médicos");
        jMenuItemCadastroMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroMedicosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroMedicos);

        jMenuItemCadastroUsuarios.setText("Cadastro Usuários");
        jMenuItemCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUsuariosActionPerformed(evt);
            }
        });
        jMenuAdministrativo.add(jMenuItemCadastroUsuarios);

        jMenuBar.add(jMenuAdministrativo);

        jMenuAgendamento.setText("Agendamento");
        jMenuBar.add(jMenuAgendamento);

        jMenuAtendimento.setText("Atendimento");
        jMenuBar.add(jMenuAtendimento);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConsultaEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaEspecialidadesActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaEspecialidades jFrameConsultaEspecialidades;
            jFrameConsultaEspecialidades = new JFrameConsultaEspecialidades(false, true);
            jFrameConsultaEspecialidades.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaEspecialidadesActionPerformed

    private void jMenuItemCadastroEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroEspecialidadesActionPerformed
        // TODO add your handling code here:
        try {
            JFrameEspecialidadesCRUD jFrameConsultaEspecialidadesCRUD;
            jFrameConsultaEspecialidadesCRUD = new JFrameEspecialidadesCRUD(null, true);
            jFrameConsultaEspecialidadesCRUD.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroEspecialidadesActionPerformed

    private void jMenuItemConsultaConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaConveniosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaConvenio jFrameConsultaConvenios;
            jFrameConsultaConvenios = new JFrameConsultaConvenio(false, true);
            jFrameConsultaConvenios.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaConveniosActionPerformed

    private void jMenuItemCadastroConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroConveniosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConvenioCRUD jFrameConvenioCRUD;
            jFrameConvenioCRUD = new JFrameConvenioCRUD(null, true);
            jFrameConvenioCRUD.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroConveniosActionPerformed

    private void jMenuItemConsultaMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaMedicosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaMedicos jFrameConsultaMedicos;
            jFrameConsultaMedicos = new JFrameConsultaMedicos(false, true);
            jFrameConsultaMedicos.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaMedicosActionPerformed

    private void jMenuItemCadastroMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroMedicosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameMedicosCRUD jFrameMedicosCRUD;
            jFrameMedicosCRUD = new JFrameMedicosCRUD(null, true);
            jFrameMedicosCRUD.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroMedicosActionPerformed

    private void jMenuItemConsultaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaUsuariosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameConsultaUsuario jFrameConsultaUsuarios;
            jFrameConsultaUsuarios = new JFrameConsultaUsuario(false, true);
            jFrameConsultaUsuarios.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemConsultaUsuariosActionPerformed

    private void jMenuItemCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUsuariosActionPerformed
        // TODO add your handling code here:
        try {
            JFrameUsuarioCRUD jFrameUsuarioCRUD;
            jFrameUsuarioCRUD = new JFrameUsuarioCRUD(null, true);
            jFrameUsuarioCRUD.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCadastroUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAdministrativo;
    private javax.swing.JMenu jMenuAgendamento;
    private javax.swing.JMenu jMenuAtendimento;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCadastroConvenios;
    private javax.swing.JMenuItem jMenuItemCadastroEspecialidades;
    private javax.swing.JMenuItem jMenuItemCadastroMedicos;
    private javax.swing.JMenuItem jMenuItemCadastroUsuarios;
    private javax.swing.JMenuItem jMenuItemConsultaConvenios;
    private javax.swing.JMenuItem jMenuItemConsultaEspecialidades;
    private javax.swing.JMenuItem jMenuItemConsultaMedicos;
    private javax.swing.JMenuItem jMenuItemConsultaUsuarios;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
